apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      restartPolicy: Always
      containers:
      - name: sampleapp
        image: docker.io/vasudevdchavan/rhel9:9.5.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
