---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manualsync-example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vasudevchavan/argo-cd.git'
    targetRevision: HEAD
    path: 'overlays/manualsync'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sampleapp
  