---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manualsync-example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vasudevchavan/Automation_scripts.git'
    targetRevision: HEAD
    path: 'sample-app'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true