---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autosync-example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vasudevchavan/argo-cd.git'
    targetRevision: HEAD
    path: '1example'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true